Repository Sharayu1071/Hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#3 please merge my pull request under hacktoberfest2022
  Web Development/Dice Game/dice1.png
  Web Development/Dice Game/dice2.png
  Web Development/Dice Game/dice3.png
  Web Development/Dice Game/dice4.png
  Web Development/Dice Game/dice5.png
  Web Development/Dice Game/dice6.png
  Web Development/Dice Game/index.html
  Web Development/Dice Game/index.js
  Web Development/Dice Game/styles.css
Labels: hacktoberfest2022-accepted, hacktoberfest2022

#7 BMICalculator.html
  Web Development/bmi.html
Labels: hacktoberfest2022

#4 Added Windows 11 clone
  Web Development/Windows11 Clone/css/style.css
  Web Development/Windows11 Clone/favicon/android-chrome-192x192.png
  Web Development/Windows11 Clone/favicon/android-chrome-512x512.png
  Web Development/Windows11 Clone/favicon/apple-touch-icon.png
  Web Development/Windows11 Clone/favicon/favicon-16x16.png
  Web Development/Windows11 Clone/favicon/favicon-32x32.png
  Web Development/Windows11 Clone/favicon/favicon.ico
  Web Development/Windows11 Clone/favicon/site.webmanifest
  Web Development/Windows11 Clone/img/bg.jpeg
  Web Development/Windows11 Clone/img/bg2.jpg
  Web Development/Windows11 Clone/img/chromeicon.png
  Web Development/Windows11 Clone/img/edgeicon.png
  Web Development/Windows11 Clone/img/favicon.ico
  Web Development/Windows11 Clone/img/recyclebinicon.png
  Web Development/Windows11 Clone/img/startmenu.PNG
  Web Development/Windows11 Clone/img/taskbar.PNG
  Web Development/Windows11 Clone/img/taskbarright.PNG
  Web Development/Windows11 Clone/index.html
  Web Development/Windows11 Clone/js/script.js
  Web Development/Windows11 Clone/video.webm
Labels: hacktoberfest-accepted, hacktoberfest2022

#12 Create linked list
  linked list
Labels: hacktoberfest-accepted, hacktoberfest2022

#11 Convert .wav file to spectrogram
  Machine Learning Projects/convert .wav file to spectrogram
Labels: hacktoberfest-accepted, hacktoberfest2022

#17 Add Integers
  Add Integers
Labels: hacktoberfest-accepted, hacktoberfest2022

#18 Merge List
  Merge List
Labels: hacktoberfest-accepted, hacktoberfest2022

#15 wieshes
  hid.html
Labels: hacktoberfest-accepted, hacktoberfest2022

#20 Digit Recognizer Project added
  Machine Learning Projects/Paint GUI and Digit Recognizer/GUI.py
  Machine Learning Projects/Paint GUI and Digit Recognizer/img/abc
  Machine Learning Projects/Paint GUI and Digit Recognizer/img/img_0.png
  Machine Learning Projects/Paint GUI and Digit Recognizer/img/img_0.pngimg_0.png
  Machine Learning Projects/Paint GUI and Digit Recognizer/mnist.h5
Labels: hacktoberfest-accepted, hacktoberfest2022

#19 Added index.html file
  fibonacci.py
  index.html
Labels: hacktoberfest-accepted, hacktoberfest2022

#21 Create doubly linked list.cpp
  doubly linked list.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#26 Climbing Stairs
  Climbing Stairs
Labels: hacktoberfest-accepted, hacktoberfest2022

#25 Remove Element
  Remove Element
Labels: hacktoberfest-accepted, hacktoberfest2022

#29 Create InfixtoPostfixConversion.cpp
  InfixtoPostfixConversion.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#30 Add files via upload
  animated.html
  no-sidebar.html
Labels: hacktoberfest-accepted, hacktoberfest2022

#32 added debug sql file
  debug.sql
Labels: hacktoberfest-accepted, hacktoberfest2022

#33 Create array.java
  array.java
Labels: hacktoberfest-accepted, hacktoberfest2022
